In [1]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
a[1, 2] # get a specific element

6

In [6]:
a[1, :] # get a specific row

array([4, 5, 6])

In [7]:
a[:, 1] # get a specific column

array([2, 5])

In [8]:
a[0, 0] = 0
a

array([[0, 2, 3],
       [4, 5, 6]])

In [9]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [10]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
after = before.reshape(4, 2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
